import tables

var cityNames* = {
    "european": [
        "Heabluff",
        "Haythorp",
        "Boomoor",
        "Frabrook",
        "Ampbluff",
        "Brethorp",
        "Nemoor",
        "Waythorp",
        "Waybluff",
        "Bywich",
        "Meastead",
        "Baygrove",
        "Soham",
        "Arbluff",
        "Peestone",
        "Brethorp",
        "Weeford",
        "Rheabrook",
        "Cheyminster",
        "Wayfield"
    ],
    "asian": [
        "Jinyi",
        "Jiayugyi",
        "Mingyi",
        "Nanchou",
        "Gyanyi",
        "Bengbo",
        "Shunyi",
        "Weifei",
        "Chunyi",
        "Xingnyi",
        "Kawani",
        "Tachino",
        "Mada",
        "Irokan",
        "Toyookashi",
        "Kamatse",
        "Togai",
        "Hari",
        "Masu",
        "Yokukin"
    ],
    "african": [
        "Lengo",
        "Msabe",
        "Bomba",
        "Chomba",
        "Mussa",
        "Mulu",
        "Mango",
        "Oyembabi",
        "Mako",
        "Kanda",
        "Swena",
        "Arnak",
        "Karna",
        "Meda",
        "Asyun",
        "Iunet",
        "Aren",
        "Asen",
        "Giza",
        "Avak"
    ],
    "middle eastern": [
        "Maha",
        "Ahlah",
        "Safir",
        "Asif",
        "Saha",
        "Mami",
        "Majmi",
        "Qali",
        "Hamra",
        "Raha",
        "Qatun",
        "Amil",
        "Shabi",
        "Ghayri",
        "Sanaa",
        "Muscat",
        "Sala",
        "Khayla",
        "Baha",
        "Nasah"
    ],
    "human": [
        "Wistow",
        "Mastow",
        "Heaton",
        "Wooford",
        "Tawold",
        "Haham",
        "Cabrook",
        "Paleah",
        "Redale",
        "Spestone",
        "Waleah",
        "Defalls",
        "Gaburh",
        "Oftun",
        "Matun",
        "Chaygate",
        "Paford",
        "Pestone",
        "Haiminster",
        "Weford"
    ],
    "elvish": [
        "Edhel",
        "Ondevrand",
        "Hilonde",
        "Eressead",
        "Gothriene",
        "Ondond",
        "Eglad",
        "Lionyamar",
        "Honyamithl",
        "Olis",
        "Forladhomb",
        "Dorwine",
        "Ellombad",
        "Enessead",
        "Erenon",
        "Onellond",
        "Egrothlon",
        "Elel",
        "Nionevriath",
        "Lothlone"
    ],
    "dwarven": [
        "Nargunulb",
        "Naledzinb",
        "Nulbilnul",
        "Khuruktharb",
        "Nuledzah",
        "Gathazar",
        "Bilgundush",
        "Shatharukth",
        "Barukthund",
        "Zaramunz",
        "Nargundush",
        "Naledzar",
        "Tumunzan",
        "Gabilnarg",
        "Zirakib",
        "Zarukthol",
        "Bunala",
        "Zinbaraz",
        "Zaddabad",
        "Gundumunz"
    ],
    "halfling": [
        "Wayley",
        "Beastone",
        "Bewood",
        "Huygrove",
        "Waham",
        "Frayford",
        "Hyheath",
        "Grapool",
        "Boowick",
        "Daford",
        "Thealey",
        "Shaiford",
        "Eampfield",
        "Beestead",
        "Arhill",
        "Fyminster",
        "Stowold",
        "Answich",
        "Souwick",
        "Kestead"
    ],
    "orcish": [
        "Lagdog",
        "Orcog",
        "Lurtzog",
        "Golurtz",
        "Muzga",
        "Agal",
        "Baga",
        "Gashagr",
        "Rat",
        "Orbash",
        "Gorbag",
        "Gorga",
        "Agal",
        "Golug",
        "Boldush",
        "Gorkil",
        "Mega",
        "Golfimb",
        "Lugdush",
        "Olfil"
    ],
    "goblin": [
        "Kran Ghognakh",
        "Vrod Grugrodh",
        "Gorrokh",
        "Mugnadh",
        "Chuzgredh",
        "Agnukh",
        "Rulbushbon",
        "Krubarard",
        "Zashban Ol",
        "Brezard Kul",
        "Urd Dhudedh",
        "Di Ghuzzel",
        "Aridh",
        "Drubokh",
        "Azug",
        "Mibudh",
        "Drorkocron",
        "Madrozzeg",
        "Azzodh Bug",
        "Rigrurd Duz"
    ],
    "gnome": [
        "Aljin",
        "Gacorin",
        "Valser",
        "Jefan",
        "Tokur",
        "Garos",
        "Bilfiz",
        "Davpip",
        "Tantor",
        "Davxif",
        "Nyssa",
        "Wromyn",
        "Rezyre",
        "Domyra",
        "Spiqys",
        "Folmiphi",
        "Daphifi",
        "Hellys",
        "Yoxi",
        "Nyzyre"
    ]
}.toTable

var deitiesList* = [
    {"name": "Paladine",
    "rule": "God of rulers and guardians",
    "alignment": "LG",
    "domain": "War"
    }.toTable,
    {"name": "Branchala",
    "rule": "God of music",
    "alignment": "NG",
    "domain": "Light"
    }.toTable,
    {"name": "Habbakuk",
    "rule": "God of animal life and see",
    "alignment": "NG",
    "domain": "Nature or Tempest"
    }.toTable,
    {"name": "Kiri-Jolith",
    "rule": "God of honor and war",
    "alignment": "LG",
    "domain": "War"
    }.toTable,
    {"name": "Majere",
    "rule": "God of meditation and order",
    "alignment": "LG",
    "domain": "Knowledge"
    }.toTable,     
    {"name": "Mishakal",
    "rule": "Goddess of healing",
    "alignment": "LG",
    "domain": "Kowledge or Life"
    }.toTable, 
    {"name": "Solinari",
    "rule": "God of good magic",
    "alignment": "LG",
    "domain": "no clerics"
    }.toTable, 
    {"name": "Gilean",
    "rule": "God of knowledge",
    "alignment": "N",
    "domain": "Kowledge"
    }.toTable, 
    {"name": "Chislev",
    "rule": "Goddess of nature",
    "alignment": "N",
    "domain": "Nature"
    }.toTable, 
    {"name": "Reorx",
    "rule": "God of craft",
    "alignment": "N",
    "domain": "Knowledge"
    }.toTable,
    {"name": "Shinare",
    "rule": "Goddess of wealth and trade",
    "alignment": "N",
    "domain": "Knowledge or Trickery"
    }.toTable,  
    {"name": "Sirrion",
    "rule": "God of fire and change",
    "alignment": "N",
    "domain": "Nature"
    }.toTable,
    {"name": "Zivilyn",
    "rule": "God of wisdom",
    "alignment": "N",
    "domain": "Kowledge"
    }.toTable,  
    {"name": "Lunitari",
    "rule": "Goddess of neutral magic",
    "alignment": "N",
    "domain": "no clerics"
    }.toTable,
    {"name": "Takhisis",
    "rule": "Goddess of night and hatred",
    "alignment": "LE",
    "domain": "Death"
    }.toTable,
    {"name": "Chemosh",
    "rule": "God of the undead",
    "alignment": "LE",
    "domain": "Death"
    }.toTable,  
    {"name": "Hiddukel",
    "rule": "God of lies and greed",
    "alignment": "CE",
    "domain": "Trickery"
    }.toTable, 
    {"name": "Morgion",
    "rule": "God of disease and secrecy",
    "alignment": "NE",
    "domain": "Death"
    }.toTable, 
    {"name": "Sargonna",
    "rule": "God of vengeance and fire",
    "alignment": "LE",
    "domain": "War"
    }.toTable, 
    {"name": "Zeboim",
    "rule": "Goddess of the sea and storm",
    "alignment": "CE",
    "domain": "Tempest"
    }.toTable, 
    {"name": "Nuitari",
    "rule": "God of evil magic",
    "alignment": "LE",
    "domain": "no clerics"
    }.toTable
]

var npcNames* = {
        "human": {
            "male": [
                "Adwan",
                "Ardlard",
                "Richye",
                "Edmund",
                "Gauward",
                "Hrihtio",
                "Gauwis Jorde",
                "Gare",
                "Rewyn",
                "Broguy Wake",
                "Berny",
                "Thelry",
                "Ether",
                "Cleavif",
                "Wealdhelm",
                "Here",
                "Ricio",
                "Graffolk",
                "Cyne",
                "Gery Toke",
                "Reder",
                "Gerey",
                "Gylip Wellsor",
                "Aler Pyley",
                "Inerth",
                "Gery",
                "George Courte",
                "Ermulf",
                "Walter Wesell",
                "Broguy Lewe"
            ],
            "female": [
                "Alyn",
                "Alfild",
                "Toney",
                "Rose",
                "Bretha",
                "Sarry Rowe",
                "Cilia",
                "Ethed",
                "Wynna",
                "Suse Marte",
                "Adgith",
                "Arurh",
                "Marger",
                "Benne Page",
                "Hilda",
                "Abeth",
                "Delme",
                "Eryet",
                "Gytha",
                "Inell",
                "Wenburg",
                "Annen",
                "Hilda",
                "Arior Mynge",
                "Wulfwe",
                "Wene",
                "Tanha",
                "Wynna",
                "Kathel Vaughey",
                "Gythuia"
            ]
        }.toTable,
        "european": {
            "male": [
                "Alas",
                "Finy",
                "Harlip Ferry",
                "Rewis",
                "Geoffry Mythey",
                "Raffolk",
                "Wilhye",
                "Tharliam",
                "Andes",
                "Narder",
                "Wisym",
                "Robern Velley",
                "Rancis",
                "Terey Bexley",
                "Narder",
                "Georguy Baile",
                "Gauwyn Pethey",
                "Gauwalt",
                "Altert",
                "Artin Benthey",
                "Johny",
                "Gery",
                "Altes",
                "Vyncent",
                "Harder",
                "Anthol",
                "Grewill",
                "Wisym None",
                "Piersym",
                "Iffin"
            ],
            "female": [
                "Eryn",
                "Enen",
                "Joane",
                "Cecie",
                "Maly",
                "Bely",
                "Abell",
                "Ellet",
                "Alil",
                "Eryel",
                "Elyn",
                "Jane Hyte",
                "Hely Kypwe",
                "Merey",
                "Suse",
                "Isan",
                "Atel Ginte",
                "Marget",
                "Joane Wyarde",
                "Cilia Elyn",
                "Cecie",
                "Malia",
                "Sybel",
                "Kathel",
                "Rix Drighte",
                "Joane",
                "Hone",
                "Mery Neson",
                "Elyn Skypwe",
                "Alys"
            ]
        }.toTable,
        "asian": {
            "male": [
                "Tao Ju-It",
                "Ge Ho-Mei",
                "Chou Tia-Lee",
                "Gu Mi-Loo",
                "Tsu Tai",
                "Tsui Huy-Wu",
                "Chua Zhe-Xi",
                "Tsi Yaan-Lu",
                "Chao Fa-Zu",
                "Zhao Ruo",
                "Hio Gui-Mou",
                "Dee Shu-Hao",
                "Fu Pie-Jai",
                "Niu Ma-Chou",
                "Hu Mi",
                "Ju Hi-Hay",
                "Kui Shao-Guo",
                "Hao Lou-Li",
                "Xue Chu-Too",
                "Chou Zhe",
                "Kaki Bashi",
                "Taga Hibei",
                "Ifuk Yoshin",
                "Kima Kichei",
                "Sukaya Suro",
                "Koda Seiko",
                "Hima Suki",
                "Toma Shunge",
                "Sate Jiri",
                "Wabu Saionji"
            ],
            "female": [
                "Tari Yuman",
                "Muraya Suki",
                "Taki Mika",
                "Orin Kicho",
                "Fuka Maru",
                "Naki Romi",
                "Toma Riko",
                "Yokan Mako",
                "Oden Nama",
                "Higa Suko",
                "Ge Yung",
                "Chao Lei-Mu",
                "Lei Lu",
                "Chao Kuei",
                "Qu Kui-Xiao",
                "Ma Li-Sa",
                "Xia Lu",
                "Ba Chao",
                "Fa Chio-Fei",
                "Lau Jia",
                "He Ci",
                "Luo Mu-La",
                "Da Hiou",
                "Chou He-Xue",
                "Lee Bao",
                "Tsui May-Lu",
                "Yuan Gui-Wa",
                "Qiu Chui-Dou",
                "Kui Te",
                "Chua Tsao-Niao"
            ]
        }.toTable,
        "african": {
            "male": [
                "Nefha",
                "Siufy",
                "Nermosy",
                "Niutashu",
                "Neshay",
                "Numha",
                "Djetherse",
                "Hibre",
                "Yuyasakheb",
                "Pepabi",
                "Chita",
                "Boba",
                "Kanda",
                "Bando",
                "Akika",
                "Boko",
                "Mule",
                "Banda",
                "Chipa",
                "Mandi",
                "Nada",
                "Kira",
                "Kabbe",
                "Okom",
                "Bedi",
                "Nyaga",
                "Kara",
                "Ilyah",
                "Muho",
                "Ayonner"
            ],
            "female": [
                "Onjong",
                "Warya",
                "Batta",
                "Iyated",
                "Ddibo",
                "Akom",
                "Oper",
                "Muni",
                "Wango",
                "Seyouma",
                "Banihay",
                "Rushasi",
                "Ketisy",
                "Spesenna",
                "Nitabu",
                "Senihay",
                "Atdjetet",
                "Tameti",
                "Nefere",
                "Were",
                "Kado",
                "Mumba",
                "Chiongo",
                "Kasa",
                "Mussa",
                "Buba",
                "Muleo",
                "Chita",
                "Mona",
                "Banda"
            ]
        }.toTable,
        "middle eastern": {
            "male": [
                "Rimee ibn Am'khiy al-Ul",
                "Lahyaa ibn Meri al-Inani",
                "Qaar'ul al-Mee",
                "Saani ibn Hali al-Ma",
                "Abu Mee'am Sa'sa al-Hamii",
                "Arfan al-Matani",
                "Abu Fiy'ry Yar'ma al-Khutifi",
                "Dooni al-Ry",
                "Ul'hyaa ibn Ha'shiy al-Medahi",
                "Reema ibn Amam al-Dhadnai",
                "Sa'sa ibn Zaafa al-Aad",
                "Imraan ibn Al'bu al-Ni",
                "Adhad ibn Abem al-Us",
                "Abu Ma'taa Bahiy al-Burai",
                "Walee ibn Yah'ma al-Yaq",
                "Kha'hyaa ibn Sa'ma al-Mee",
                "Abu Riya'mee Ufeen al-Dahai",
                "Abu Taa'am Bedy al-Athati",
                "Khayri ibn Suoudaa al-Mee",
                "Khaari al-Sa",
                "Abu Fi'ad Khaani al-Ud",
                "Isazz ibn Anan al-Mushai",
                "Ad'aan al-Sa",
                "Abu Fee'jy Mee'sa al-Ma",
                "Abu Haasha Nooha al-Ry",
                "Midiyaa al-Sa",
                "Ib'sa al-Khinai",
                "Ah'bay al-Ah",
                "Ma'ha ibn Salee al-Wiya",
                "Abu Fiy'ma Haamee al-Khobii"
            ],
            "female": [
                "Umm Ha'qat Kara al-Ma",
                "Umm Sama Samay al-Bahai",
                "Ha'siya bint Ma'di al-Hamrai",
                "Atin bint Mee'wiya al-Ah",
                "Ah'siya bint Wajy al-Mudhai",
                "Ra'ziya al-Hafjii",
                "Wiyaha al-Misaiqi",
                "Umm In'mee Sa'ba al-Barkai",
                "Ba'na bint Mufa al-Ha",
                "Umm Fa'wiya Ha'ja al-Manai",
                "Umm Jy'shyaa Waha al-Abahi",
                "Ka'ha bint Haldy al-Ashbahi",
                "Na'fa al-Masuli",
                "Umm Ustad Fa'ah al-Jawfufi",
                "Umm Rahyaa Ma'ma al-Daydahi",
                "Umm Ad'hiy Saha al-Baquri",
                "Gha'ah bint Atim al-Mudhai",
                "Sala al-Hamai",
                "Baha bint Aleem al-Ma",
                "Sa'ra al-Misayli",
                "Mana bint Abduq al-Ry",
                "Umm Adir Worda al-Khaylai",
                "Ghara bint Wiya'al al-Khahai",
                "Fara al-Khy",
                "Umm Rahiy Ka'la al-Majmai",
                "Hahra bint Ma'bu al-Kalbaii",
                "Laha al-Wiya",
                "Ra'yah bint Bay'an al-Surii",
                "Faha al-Aah",
                "Bara bint Zuhyaa al-Mochai"
            ]
        }.toTable,
        "elvish": {
            "male": [
                "Enethorm",
                "Findire",
                "Ranwe",
                "Ophimir",
                "Celebre",
                "Miladir",
                "Galemmion",
                "Mili",
                "Eluril",
                "Elurgon",
                "Eamradhor",
                "Pengolfing",
                "Glinarfing",
                "Ranwe",
                "Hirandor",
                "Daerodre",
                "Galemmagl",
                "Gimlorfean",
                "Carodre",
                "Thingilgelm",
                "Pengali",
                "Minerdhil",
                "Egos",
                "Galadir",
                "Anthindin",
                "Annaeg",
                "Enweneth",
                "Celinel",
                "Saerasaer",
                "Elroron"
            ],
            "female": [
                "Neluthel",
                "Nellalwe",
                "Iris",
                "Arwel",
                "Enwel",
                "Imroth",
                "Findanye",
                "Imrotel",
                "Findalye",
                "Gilmarie",
                "Gilmithrie",
                "Arwel",
                "Gilminye",
                "Nelaser",
                "Ilas",
                "Galote",
                "Indellas",
                "Nelote",
                "Indiriel",
                "Arieris",
                "Alwel",
                "Elel",
                "Laserie",
                "Niserie",
                "Findelye",
                "Nimluthel",
                "Inyebrian",
                "Arwen",
                "Areldas",
                "Serie"
            ]
        }.toTable,
        "dwarven": {
            "male": [
                "Orin",
                "Kada",
                "Zuri",
                "Undim",
                "Dainan",
                "Gluri",
                "Bori",
                "Gamin",
                "Furi",
                "Banan",
                "Thali",
                "Gwali",
                "Thrinan",
                "Dwari",
                "Ugmal",
                "Gili",
                "Imlin",
                "Khundu",
                "Thainan",
                "Zigil",
                "Gamul",
                "Sanzir",
                "Gili",
                "Bali",
                "Khatur",
                "Grasanz",
                "Bari",
                "Khari",
                "Shimin",
                "Dinan"
            ],
            "female": [
                "Gili",
                "Alin",
                "Thrinarv",
                "Gluri",
                "Fundu",
                "Nanain",
                "Zigam",
                "Grori",
                "Mali",
                "Umral",
                "Kali",
                "Zaghark",
                "Rinarv",
                "Askar",
                "Undin",
                "Fundu",
                "Kada",
                "Kharkad",
                "Dinan",
                "Dwali",
                "Khali",
                "Alin",
                "Kunan",
                "Fari",
                "Gili",
                "Bari",
                "Ziri",
                "Khari",
                "Nanain",
                "Thali"
            ]
        }.toTable,
        "halfling": {
            "male": [
                "Ames",
                "Ancip",
                "Rugo Fairboph",
                "Breward",
                "Gauward",
                "Mado Bairnell",
                "Georguy Alard",
                "Berny Bowe",
                "Adolph",
                "Narder",
                "Fastolm",
                "Symund Mylne",
                "Armas Under",
                "Nichye",
                "Hamond Kelle",
                "Riffolk",
                "Pinas",
                "Hildo",
                "Symas",
                "Greyny Bourne",
                "Cotme Bolge",
                "Tharder",
                "Vyncent",
                "Fastar",
                "Leony Borne",
                "Boldo Chinell",
                "Grobert Wyare",
                "Garas",
                "Reyny",
                "Hildo"
            ],
            "female": [
                "Arida",
                "Elin Dowson",
                "Joane",
                "Abel",
                "Lice Tharcey",
                "Wene Hammayc",
                "Ener Basi",
                "Eryet",
                "Sabeatr",
                "Joyce Salte",
                "Primay",
                "Sybil",
                "Athel",
                "Cece Elmer",
                "Amel",
                "Nora",
                "Efrix",
                "Anet Yourner",
                "Iden",
                "Sarra",
                "Mentha Buck",
                "Lila Gamgee",
                "Aver Gammarch",
                "Cecie",
                "Kather",
                "Belly",
                "Bella Bairnell",
                "Izan",
                "Mara",
                "Elel"
            ]
        }.toTable,
        "orcish": {
            "male": [
                "Orcod",
                "Golugd",
                "Snakhak",
                "Balug",
                "Rodush",
                "Gradbalcm",
                "Lagduf",
                "Ufthakh",
                "Lurtzog",
                "Buga",
                "Snaga",
                "Baga",
                "Obakh",
                "Golfimb",
                "Lukil",
                "Balurtz",
                "Mega",
                "Olfil",
                "Rodush",
                "Bolga",
                "Lagduf",
                "Gorbold",
                "Lukil",
                "Rishnag",
                "Gorbolg",
                "Golugd",
                "Gorbug",
                "Orkil",
                "Shagrat",
                "Lugdush"
            ],
            "female": [
                "Golugd",
                "Lurtzog",
                "Lukil",
                "Rat",
                "Boldog",
                "Luga",
                "Uglurtz",
                "Gorbold",
                "Lugduf",
                "Snakhur",
                "Bulagd",
                "Muzga",
                "Rat",
                "Shagrod",
                "Gorkil",
                "Azol",
                "Balcmauh",
                "Ugdurtz",
                "Shurat",
                "Gorga",
                "Shagrod",
                "Gorga",
                "Mauhak",
                "Gashagr",
                "Balcmeg",
                "Snakhur",
                "Mauhagr",
                "Snakhak",
                "Gashur",
                "Lukil"
            ]
        }.toTable,
        "goblin": {
            "male": [
                "Bink",
                "Jiozz",
                "Fukz",
                "Besz",
                "Osb",
                "Dottulx",
                "Eezlukt",
                "Uittiork",
                "Juibhot",
                "Kleagras",
                "Fus",
                "Pax",
                "Wruigz",
                "Vark",
                "Gurd",
                "Gniesmalb",
                "Wemvilx",
                "Frogbeerk",
                "Steazmeank",
                "Ieklaasz",
                "Bunk",
                "Sreer",
                "Pogs",
                "Plikx",
                "Rork",
                "Fushiang",
                "Osmocs",
                "Cognerd",
                "Gluismieq",
                "Stregriok"
            ],
            "female": [
                "Phothea",
                "Qiazz",
                "Frens",
                "Starxi",
                "Stalm",
                "Givreq",
                "Prarranq",
                "Fihkiahi",
                "Bropsus",
                "Wrytturtia",
                "Heeg",
                "Wuft",
                "Duldee",
                "Jiehx",
                "Praasxia",
                "Vamiag",
                "Trirzusz",
                "Bismerx",
                "Topalt",
                "Khoivuisxi",
                "Ih",
                "Flus",
                "Aath",
                "Aaq",
                "Tryrxa",
                "Swiegifz",
                "Ukleel",
                "Vigziart",
                "Crunoh",
                "Srestuizzea"
            ]
        }.toTable,
        "gnome": {
            "male": [
                "Pakart",
                "Gegnag",
                "Bobkit",
                "Slalbest",
                "Zuknet",
                "Wombegiess",
                "Klanzunyst",
                "Haloruss",
                "Sculibnert",
                "Dilienkkot",
                "Gnansnir",
                "Franjeg",
                "Milvier",
                "Hakap",
                "Pokwar",
                "Slemzunet",
                "Smaabbrumog",
                "Snooneemmeg",
                "Liefankkack",
                "Slilonsmac",
                "Zimzyt",
                "Gnamdock",
                "Pimwack",
                "Zurart",
                "Danbeem",
                "Cekwacem",
                "Gneemdiegoc",
                "Knofangnist",
                "Dyvomter",
                "Liwydbaig"
            ],
            "female": [
                "Bluvith",
                "Wipnam",
                "Blemwip",
                "Thabnath",
                "Gidla",
                "Fapwawaa",
                "Caddnawoll",
                "Evallner",
                "Flonaallbe",
                "Snowalwi",
                "Phapwuss",
                "Ningnith",
                "Phobblyp",
                "Clalvu",
                "Blelwan",
                "Maivemil",
                "Flupniwe",
                "Flifuri",
                "Thenongni",
                "Felimda",
                "Medwiss",
                "Snyngnip",
                "Melkass",
                "Slinsmam",
                "Melmuth",
                "Phankaasos",
                "Phailvove",
                "Temaiddlo",
                "Fleweppir",
                "Clevaablel"
            ]
        }.toTable
    }.toTable